/**
 * Additional facts — batch 2 (30 more per category)
 * Merged by generate-facts.js to reach 500 total
 */
'use strict';

const EXTRA_FACTS = {
    Science: [
        ["Helium was discovered on the Sun before it was found on Earth.", "Royal Society"],
        ["A tablespoon of a neutron star material weighs about 1 billion tons.", "NASA"],
        ["Electrons can exist in two places at the same time — quantum superposition.", "CERN"],
        ["The human genome contains about 3 billion base pairs of DNA.", "Human Genome Project"],
        ["Gravity travels at the speed of light.", "Einstein"],
        ["There are more bacteria in your mouth than there are people on Earth.", "NIH"],
        ["If the Sun were the size of a front door, Earth would be the size of a nickel.", "NASA"],
        ["Static electricity can reach voltages of 25,000 volts.", "Physics"],
        ["Water expands by about 9% when it freezes into ice.", "Chemistry"],
        ["A single human cell contains about 6 feet of DNA when uncoiled.", "NIH"],
        ["The speed of light in a vacuum is exactly 299,792,458 meters per second.", "NIST"],
        ["Black holes can evaporate over time through Hawking radiation.", "Stephen Hawking"],
        ["Absolute zero is −273.15°C — the lowest possible temperature.", "Thermodynamics"],
        ["A googol is the number 1 followed by 100 zeros.", "Mathematics"],
        ["The Earth's core is as hot as the surface of the Sun — about 5,500°C.", "USGS"],
        ["Sound cannot travel through a vacuum — there are no particles to vibrate.", "Physics"],
        ["Lasers can be cooled to temperatures colder than outer space.", "MIT"],
        ["The strongest known material is graphene — 200 times stronger than steel.", "Materials Science"],
        ["Time moves slightly faster at the top of a building than at the bottom.", "General Relativity"],
        ["Every atom in your body is billions of years old.", "Astrophysics"],
        ["Quantum entanglement allows particles to communicate instantaneously across any distance.", "Quantum Physics"],
        ["The Higgs boson was predicted in 1964 but not discovered until 2012.", "CERN"],
        ["A single lightning bolt can heat the air around it to 30,000 Kelvin.", "NOAA"],
        ["The Fibonacci sequence appears naturally in sunflowers, pinecones, and shells.", "Mathematics"],
        ["Supercooled water can remain liquid below 0°C until disturbed.", "Physics"],
        ["Rubber bands last longer when refrigerated.", "Polymer Science"],
        ["The human body emits a small amount of visible light — too faint for eyes to see.", "Kyoto University"],
        ["A piece of paper cannot be folded more than about 7 times by hand.", "Mathematics"],
        ["Quantum computers can solve certain problems millions of times faster than classical ones.", "IBM"],
        ["The color orange was named after the fruit, not the other way around.", "Etymology"]
    ],
    History: [
        ["The Great Wall of China is not visible from space with the naked eye.", "NASA"],
        ["Ancient Greeks invented the vending machine — it dispensed holy water.", "Hero of Alexandria"],
        ["Heroin was once sold as a cough suppressant by Bayer.", "Bayer Archives"],
        ["The first fax machine was invented in 1843, before the telephone.", "Alexander Bain"],
        ["Ancient Romans used urine to whiten their teeth.", "Historical Records"],
        ["Coca-Cola originally contained cocaine — about 9 mg per glass.", "Smithsonian"],
        ["The last country to abolish slavery was Mauritania in 1981.", "UN"],
        ["The world's oldest continuously operating restaurant opened in Madrid in 1725.", "Sobrino de Botín"],
        ["Before alarm clocks, people hired 'knocker-uppers' to tap on their windows.", "Industrial History"],
        ["The first traffic light was installed in London in 1868 — and it exploded.", "Transport History"],
        ["Ancient Egyptians invented the 365-day calendar.", "Egyptian History"],
        ["The Library of Alexandria may have contained over 400,000 scrolls.", "Ancient History"],
        ["Pirates wore eye patches to keep one eye adapted to darkness below deck.", "Maritime History"],
        ["The shortest reign of a monarch was 20 minutes — Louis XIX of France.", "French Records"],
        ["Ancient Romans had heated floors called hypocausts.", "Archaeological Records"],
        ["The Titanic's band really did play as the ship sank.", "Survivor Accounts"],
        ["Ketchup was invented in China as a fermented fish sauce called 'ke-tsiap'.", "Food History"],
        ["The first Olympic marathon in 1896 was won by a Greek water carrier.", "Olympic Records"],
        ["In 1835, the US national debt was $0 — the only time in history.", "US Treasury"],
        ["The Rosetta Stone was actually a tax document.", "British Museum"],
        ["Roman Emperor Caligula made his horse a senator.", "Roman History"],
        ["The oldest known joke is from 1900 BC Sumeria — it's a fart joke.", "Academic Records"],
        ["Medieval Europeans believed tomatoes were poisonous for 200 years.", "Food History"],
        ["The first photograph of a person was taken accidentally in 1838.", "History of Photography"],
        ["Vikings navigated using sunstones that polarize light on cloudy days.", "Marine Archaeology"],
        ["The original Monopoly game was designed to teach about land monopolies.", "Lizzie Magie"],
        ["Ancient Persians debated ideas twice — once sober and once drunk.", "Herodotus"],
        ["The chainsaw was originally invented for childbirth assistance.", "Medical History"],
        ["During Prohibition, the US government poisoned industrial alcohol, killing thousands.", "Historical Records"],
        ["Cleopatra spoke at least 9 languages.", "Plutarch"]
    ],
    Nature: [
        ["A single oak tree can produce 70,000 acorns in a year.", "Forestry"],
        ["The Great Barrier Reef is the largest living structure visible from space.", "NASA"],
        ["Venus flytraps can count — they only snap shut after two touches within 20 seconds.", "Botany"],
        ["Rainforests produce about 28% of the world's oxygen.", "WWF"],
        ["Some jellyfish are immortal — Turritopsis dohrnii can revert to its juvenile stage.", "Marine Biology"],
        ["The deepest point in the ocean is Challenger Deep at 36,000 feet.", "NOAA"],
        ["A cubic mile of seawater contains about 25 tons of gold.", "USGS"],
        ["Trees communicate through underground fungal networks called 'Wood Wide Web'.", "Ecology"],
        ["The oldest known fossil is 3.7 billion years old.", "Paleontology"],
        ["Snowflakes always have six sides due to the molecular structure of ice.", "Crystallography"],
        ["An average cumulonimbus cloud weighs about 1.1 million pounds.", "NOAA"],
        ["The Atacama Desert in Chile went without rain for 400 years.", "Climate Science"],
        ["Bamboo releases 35% more oxygen than equivalent trees.", "Environmental Science"],
        ["The largest flower in the world, Rafflesia, smells like rotting flesh.", "Botany"],
        ["Earth's magnetic field has flipped hundreds of times in its history.", "Geophysics"],
        ["There are more microbes in a teaspoon of soil than people on Earth.", "Microbiology"],
        ["The longest recorded earthquake lasted 10 minutes — the 2004 Indian Ocean quake.", "USGS"],
        ["Some caves contain crystals large enough to walk through — Naica Mine, Mexico.", "Geology"],
        ["Lake Nyos in Cameroon silently killed 1,700 people with CO2 in 1986.", "Geology"],
        ["The Northern Lights occur about 60-200 miles above Earth's surface.", "NASA"],
        ["Petrified wood is millions of years old but can look freshly cut.", "Paleontology"],
        ["Quicksand is rarely more than a few feet deep — you can't fully sink.", "Physics"],
        ["The loudest natural sound ever recorded was Krakatoa's eruption in 1883.", "USGS"],
        ["Some species of grass can grow in volcanic lava fields within months.", "Ecology"],
        ["Earth's oceans are about 97% of all water on the planet.", "USGS"],
        ["The tallest waterfall, Angel Falls, drops 3,212 feet.", "Geography"],
        ["Sea levels were about 400 feet lower during the last Ice Age.", "Climate Science"],
        ["Some rocks in Death Valley appear to move on their own — they're pushed by ice.", "NASA"],
        ["The largest hailstone ever recorded weighed over 2 pounds.", "NOAA"],
        ["Approximately 1,500 active volcanoes exist on Earth's surface.", "USGS"]
    ],
    Space: [
        ["The Sun makes up 99.86% of the total mass of the solar system.", "NASA"],
        ["A day on Pluto is 153 hours long.", "NASA"],
        ["The observable universe has a diameter of about 93 billion light-years.", "Cosmology"],
        ["There are rogue planets floating through space not orbiting any star.", "Astronomy"],
        ["The temperature in space can range from −270°C to thousands of degrees near stars.", "NASA"],
        ["Mars has the tallest volcano and deepest canyon in the solar system.", "NASA"],
        ["The closest star to Earth (besides the Sun) is Proxima Centauri — 4.2 light-years away.", "ESO"],
        ["A pulsar spins so fast it can rotate 716 times per second.", "NASA"],
        ["There may be more Earth-like planets than grains of sand on all our beaches.", "Kepler Mission"],
        ["GPS satellites must account for Einstein's relativity to stay accurate.", "General Relativity"],
        ["The Hubble Space Telescope can see galaxies 13.4 billion light-years away.", "NASA"],
        ["Io, Jupiter's moon, has over 400 active volcanoes.", "NASA"],
        ["Space junk travels at 17,500 mph — even a paint chip can damage a spacecraft.", "ESA"],
        ["The core of Jupiter may be a giant diamond.", "Planetary Science"],
        ["Venus rotates backwards compared to most planets — the Sun rises in the west.", "NASA"],
        ["Titan, Saturn's moon, has liquid methane lakes and rivers.", "Cassini Mission"],
        ["The Parker Solar Probe is the fastest human-made object at 430,000 mph.", "NASA"],
        ["A magnetar's magnetic field is strong enough to erase a credit card from halfway across the solar system.", "NASA"],
        ["The cosmic microwave background radiation is the oldest light in the universe — 13.8 billion years old.", "COBE"],
        ["There could be up to 2 trillion galaxies in the observable universe.", "Hubble"],
        ["An astronaut's height can increase by up to 3% in space.", "NASA"],
        ["The Oort Cloud extends nearly a light-year from the Sun.", "Astronomy"],
        ["Europa, Jupiter's moon, may have more water than all of Earth's oceans.", "NASA"],
        ["Black holes don't actually suck — objects fall into them due to gravity.", "Astrophysics"],
        ["The largest known void in space, the Boötes Void, is 330 million light-years across.", "Astronomy"],
        ["Solar flares can release energy equivalent to millions of nuclear bombs.", "NASA"],
        ["Olympus Mons on Mars is so large that its base would cover most of France.", "NASA"],
        ["If you fell into a black hole, time would slow down infinitely for outside observers.", "General Relativity"],
        ["The James Webb Space Telescope orbits 1 million miles from Earth.", "NASA"],
        ["Comets glow because the Sun vaporizes their ice, creating a luminous tail.", "Astronomy"]
    ],
    "Human Body": [
        ["The liver can regenerate itself from as little as 25% of its original tissue.", "NIH"],
        ["Humans are bioluminescent — we glow in the dark, but 1000× too dim to see.", "Kyoto University"],
        ["The brain can process an image in as little as 13 milliseconds.", "MIT"],
        ["Your tongue print is as unique as your fingerprint.", "Biometrics"],
        ["The small intestine is about 20 feet long — longer than a school bus.", "NIH"],
        ["Humans can detect over 1 trillion different smells.", "Rockefeller University"],
        ["Goosebumps are an evolutionary leftover from when humans had thick body hair.", "Evolution"],
        ["The average person produces enough saliva to fill 2 swimming pools in a lifetime.", "Dental Research"],
        ["Bone is 5 times stronger than steel bar of the same weight.", "Materials Science"],
        ["Your body replaces all its outer skin cells every 2-4 weeks.", "Dermatology"],
        ["The human brain has about 86 billion neurons.", "Neuroscience"],
        ["Stomach acid is strong enough to dissolve zinc.", "Chemistry"],
        ["Humans can survive with only one kidney, one lung, and half a brain.", "Medical Science"],
        ["Your nose can remember 50,000 different scents.", "Olfaction Research"],
        ["The average adult skeleton weighs about 3-5 kg.", "Anatomy"],
        ["Blood makes a complete circuit of your body in about 60 seconds.", "Cardiology"],
        ["The enamel on teeth is the hardest substance in the human body.", "Dental Science"],
        ["Humans share about 98.7% of their DNA with chimpanzees.", "Genetics"],
        ["Your eyes can distinguish about 10 million different colors.", "Neuroscience"],
        ["The pineal gland in your brain produces melatonin to regulate sleep.", "Endocrinology"],
        ["Crying releases stress hormones — it actually helps you feel better.", "Psychology"],
        ["The average person blinks about 15-20 times per minute.", "Ophthalmology"],
        ["Your heart creates enough pressure to squirt blood 30 feet.", "Cardiology"],
        ["Humans and giraffes have the same number of neck vertebrae — seven.", "Anatomy"],
        ["Babies are born with around 10,000 taste buds — adults have about 5,000.", "Physiology"],
        ["A cough can travel at speeds up to 50 mph.", "Pulmonology"],
        ["It's impossible to hum while holding your nose.", "Anatomy"],
        ["The human body contains enough fat to make seven bars of soap.", "Chemistry"],
        ["Your left lung is smaller than your right to make room for your heart.", "Anatomy"],
        ["Every person has a unique smell — except identical twins.", "Genetics"]
    ],
    Animals: [
        ["A group of owls is called a 'parliament'.", "Ornithology"],
        ["Wombat poop is cube-shaped to prevent it from rolling away.", "Biology"],
        ["Honey badgers can withstand venomous snake bites.", "Zoology"],
        ["The mimic octopus can impersonate over 15 different species.", "Marine Biology"],
        ["Electric eels can generate up to 860 volts of electricity.", "Biology"],
        ["A flea can jump up to 150 times its own body length.", "Entomology"],
        ["Cheetahs can't roar — they chirp and purr instead.", "Zoology"],
        ["A hornet's nest can contain up to 700 workers.", "Entomology"],
        ["Lobsters taste with their feet.", "Marine Biology"],
        ["Prairie dogs have a complex language with words for specific predators.", "Animal Behavior"],
        ["Cats have a specialized collarbone that allows them to always land on their feet.", "Veterinary Science"],
        ["The pistol shrimp creates a bubble that reaches 4,700°C — hotter than the Sun's surface.", "Marine Biology"],
        ["Elephants can hear through their feet via vibrations.", "Zoology"],
        ["Spiders can fly by releasing silk threads that catch the wind — 'ballooning'.", "Arachnology"],
        ["Cuttlefish have three hearts and green blood.", "Marine Biology"],
        ["A group of ravens is called an 'unkindness'.", "Ornithology"],
        ["Dogs can smell time — they detect the decay rate of human scent.", "Animal Cognition"],
        ["Dolphins have been observed giving each other names using unique whistle patterns.", "Marine Biology"],
        ["The Arctic Tern migrates 44,000 miles each year — pole to pole.", "Ornithology"],
        ["Male seahorses are the ones who get pregnant and give birth.", "Marine Biology"],
        ["Sloths can take up to 30 days to digest a single leaf.", "Zoology"],
        ["Bats are the only mammals capable of sustained flight.", "Zoology"],
        ["A chameleon's tongue can be twice the length of its body.", "Herpetology"],
        ["Woodpeckers have a special skull structure that absorbs impact shock.", "Ornithology"],
        ["Starfish don't have brains — they use their nervous system to sense the environment.", "Marine Biology"],
        ["Blue whales' heartbeats can be detected from over 2 miles away.", "Marine Biology"],
        ["Some species of jellyfish are older than dinosaurs.", "Paleontology"],
        ["A group of porcupines is called a 'prickle'.", "Zoology"],
        ["Platypuses can detect electrical signals from prey using their bills.", "Zoology"],
        ["Ants can lift objects 50 times their own body weight.", "Entomology"]
    ],
    Technology: [
        ["The first computer mouse was made of wood.", "Doug Engelbart, 1964"],
        ["Over 4 billion people use the internet — more than half the world's population.", "ITU"],
        ["The first domain name ever registered was symbolics.com in 1985.", "Internet History"],
        ["A modern smartphone has more computing power than all of NASA in 1969.", "NASA"],
        ["The world produces about 2.5 quintillion bytes of data every day.", "IBM"],
        ["There are about 40 times more lines of code in a modern car than in a fighter jet.", "Software Engineering"],
        ["The first digital camera was built by Kodak in 1975 and weighed 8 pounds.", "Kodak"],
        ["Bluetooth is named after a 10th-century Danish king — Harald Bluetooth.", "Ericsson"],
        ["Over 6 million text messages are sent every minute worldwide.", "Telecommunications"],
        ["The first ever computer bug was an actual moth found in a relay.", "Grace Hopper"],
        ["YouTube's first video 'Me at the Zoo' has over 300 million views.", "YouTube"],
        ["95% of all emails sent are spam.", "Cybersecurity Reports"],
        ["The term 'robot' comes from the Czech word 'robota' meaning forced labor.", "Karel Čapek"],
        ["The world's first webcam watched a coffee pot at Cambridge University.", "University of Cambridge"],
        ["There are more LEGO minifigures than real people on Earth.", "LEGO"],
        ["The average person checks their phone about 96 times per day.", "Asurion Research"],
        ["Amazon ships about 1.6 million packages per day.", "Amazon"],
        ["The entire English Wikipedia could fit on a 22 GB USB drive.", "Wikipedia"],
        ["Moore's Law predicted computing power doubles every 2 years — it held for 50+ years.", "Intel"],
        ["The longest phone call ever lasted 46 hours and 12 minutes.", "Guinness"],
        ["Netflix uses about 15% of the world's internet bandwidth.", "Sandvine"],
        ["The Firefox logo isn't actually a fox — it's a red panda.", "Mozilla"],
        ["About 5 billion YouTube videos are watched every single day.", "YouTube"],
        ["The first Apple computer was built in a garage and sold for $666.66.", "Apple"],
        ["Google's PageRank algorithm was named after Larry Page, not web pages.", "Google"],
        ["The average lifespan of a website is about 2-3 years before major redesign.", "Web Design"],
        ["There are more than 1.8 billion websites online, but most are inactive.", "Internet Live Stats"],
        ["E-sports prize pools now exceed $40 million for single tournaments.", "Esports"],
        ["Self-driving cars generate about 4 TB of data per day.", "Automotive Tech"],
        ["The world's most powerful supercomputer can perform over 1 exaflop per second.", "TOP500"]
    ],
    Food: [
        ["Saffron is more expensive per gram than gold.", "Spice Trade"],
        ["Cast iron skillets can leach iron into food — which is actually beneficial.", "Nutrition"],
        ["Vanilla is the second most expensive spice after saffron.", "Food Industry"],
        ["A single fast food hamburger can contain meat from over 100 different cows.", "Food Safety"],
        ["Bananas are berries, but raspberries are not.", "Botany"],
        ["Humans are the only species that drink milk from other animals.", "Biology"],
        ["Eating too many carrots can turn your skin orange — carotenosis.", "Dermatology"],
        ["McDonald's sells about 75 burgers per second worldwide.", "McDonald's"],
        ["The world's most expensive pizza costs $12,000 — topped with caviar and gold.", "Guinness"],
        ["Pineapple contains bromelain, an enzyme that digests protein — it eats you back.", "Biochemistry"],
        ["Almonds are members of the peach family.", "Botany"],
        ["Spam (the canned meat) is considered a delicacy in South Korea.", "Food Culture"],
        ["Honey is the only food made by an insect that humans eat.", "Entomology"],
        ["The world's hottest pepper is 200 times hotter than a jalapeño.", "Food Science"],
        ["Astronaut ice cream was never actually eaten in space.", "NASA"],
        ["A watermelon is 92% water.", "Nutrition"],
        ["The world eats about 1 billion pizzas per year.", "Food Industry"],
        ["Figs can contain dead wasps — they're pollinated by fig wasps.", "Botany"],
        ["Corn always has an even number of rows.", "Agriculture"],
        ["The first canned food was patented 48 years before the can opener.", "Invention History"],
        ["Dark chocolate contains more antioxidants than blueberries.", "Nutrition"],
        ["Japan has more Michelin-starred restaurants than any country — beating France.", "Michelin"],
        ["Coffee beans are technically seeds of coffee cherries.", "Botany"],
        ["The average American eats about 35 tons of food in their lifetime.", "FDA"],
        ["Bread was used as an eraser before rubber erasers were invented.", "History"],
        ["MSG was discovered by a Japanese chemist studying seaweed in 1908.", "Food Science"],
        ["The oldest bottle of wine ever found is over 1,650 years old.", "Archaeology"],
        ["Cauliflower comes in purple, orange, and green varieties.", "Agriculture"],
        ["Oysters can change gender multiple times during their lifetime.", "Marine Biology"],
        ["Cinnamon was once more valuable than silver in ancient Egypt.", "Trade History"]
    ],
    Geography: [
        ["Indonesia has more than 17,000 islands.", "Geography"],
        ["The Nile is the longest river at 4,130 miles, but the Amazon carries more water.", "USGS"],
        ["Mount Chimborazo in Ecuador is technically closer to space than Everest.", "Geodesy"],
        ["There are 14 mountains taller than 8,000 meters — all in Asia.", "Mountaineering"],
        ["The Caspian Sea is the world's largest lake despite being called a sea.", "Geography"],
        ["Alaska is simultaneously the most northern, western, AND eastern US state.", "Geography"],
        ["The Great Blue Hole in Belize is a 407-foot deep underwater sinkhole.", "Marine Geology"],
        ["Lesotho and Vatican City are countries entirely surrounded by a single country.", "Geography"],
        ["The Sahara Desert was green and lush just 6,000 years ago.", "Paleoclimatology"],
        ["Point Nemo in the Pacific is the farthest point from any land — 1,670 miles.", "Geography"],
        ["Brazil is larger than the contiguous 48 US states.", "Geography"],
        ["The Danakil Depression in Ethiopia is one of the hottest places on Earth.", "Climate"],
        ["Norway's coastline, if stretched out, would reach halfway around the Earth.", "Geography"],
        ["The longest international border is between Canada and the United States.", "Geography"],
        ["There's a sea of stars in the Maldives caused by bioluminescent plankton.", "Marine Biology"],
        ["Bhutan measures national success by Gross National Happiness instead of GDP.", "Economics"],
        ["The driest place on Earth isn't the Sahara — it's Antarctica's Dry Valleys.", "Climate"],
        ["Map projections make Africa look much smaller than it is — it's massive.", "Cartography"],
        ["Sweden has about 267,570 islands — more than any country except Indonesia.", "Geography"],
        ["The Panama Canal saves ships 7,872 miles of travel around South America.", "Engineering"],
        ["Tokyo is the most populated city in the world with 37+ million people.", "Demographics"],
        ["There are underground rivers flowing beneath the Sahara Desert.", "Hydrogeology"],
        ["Tuvalu earns millions from licensing its .tv internet domain.", "Economics"],
        ["The Ring of Fire contains 75% of the world's active volcanoes.", "Geology"],
        ["Chile is so long and narrow that 4,300 km of its length is coast.", "Geography"],
        ["Lake Superior contains 10% of the world's surface fresh water.", "USGS"],
        ["The border between Belgium and the Netherlands goes through some buildings.", "Geography"],
        ["Earth's tectonic plates move about as fast as your fingernails grow.", "Geology"],
        ["Over 80% of the ocean floor is still unmapped and unexplored.", "NOAA"],
        ["Greenland cannot melt into the ocean — it would raise sea levels by 24 feet.", "Climate Science"]
    ],
    "Pop Culture": [
        ["The term 'binge-watch' was added to the dictionary in 2015.", "Oxford Dictionary"],
        ["The Simpsons has accurately predicted numerous real-world events.", "Pop Culture"],
        ["Tetris is the best-selling video game of all time with 500 million copies.", "Gaming"],
        ["The word 'meme' was coined by Richard Dawkins in 1976.", "The Selfish Gene"],
        ["Harry Potter books have been translated into 80 languages.", "Publishing"],
        ["Darth Vader only has 12 minutes of screen time in the original Star Wars.", "Film Analysis"],
        ["The Oscar statuette weighs 8.5 pounds and is gold-plated bronze.", "Academy of Motion Pictures"],
        ["Michael Jackson's Thriller remains the best-selling album ever at 70 million copies.", "RIAA"],
        ["The first video game, Spacewar!, was created in 1962 at MIT.", "Computer History"],
        ["Friends' cast negotiated to each earn $1 million per episode in their final season.", "Entertainment"],
        ["The Marvel Cinematic Universe has grossed over $29 billion worldwide.", "Box Office"],
        ["Super Mario was originally a carpenter, not a plumber.", "Nintendo"],
        ["The Game of Thrones finale was watched by 19.3 million people.", "HBO"],
        ["J.K. Rowling was rejected by 12 publishers before Harry Potter was accepted.", "Publishing"],
        ["Comic Sans was designed for Microsoft Bob's cartoon dog in 1994.", "Typography"],
        ["The most-played song on Spotify is 'Blinding Lights' by The Weeknd.", "Spotify"],
        ["Disney World is roughly the same size as San Francisco.", "Disney"],
        ["The first emoji set was created by a Japanese artist in 1999 — it had 176 icons.", "Design"],
        ["Breaking Bad's finale had a 9.9/10 rating on IMDb.", "IMDb"],
        ["The Like button on Facebook was almost called the 'Awesome' button.", "Facebook"],
        ["Netflix started as a DVD rental-by-mail service in 1997.", "Netflix"],
        ["The @ symbol's original use was to represent the price 'at' per unit.", "Typography"],
        ["GIF stands for Graphics Interchange Format — and its creator says it's pronounced 'jif'.", "CompuServe"],
        ["The first tweet ever was 'just setting up my twttr' by Jack Dorsey.", "Twitter"],
        ["YouTube was originally designed as a dating website.", "YouTube"],
        ["Pikachu's name comes from Japanese: 'pika' (sparkle) and 'chu' (squeak).", "Pokémon"],
        ["The first app ever downloaded from the App Store was a free productivity app.", "Apple"],
        ["Candy Crush generates about $1 billion in revenue per year.", "Gaming Industry"],
        ["Rick Astley's 'Never Gonna Give You Up' has over 1.5 billion YouTube views.", "YouTube"],
        ["The word 'podcast' is a combination of 'iPod' and 'broadcast'.", "Media"]
    ]
};

/* istanbul ignore next */
if (typeof module !== 'undefined') {
    module.exports = { EXTRA_FACTS };
}
