/**
 * Additional facts — batch 3 (25 more per category, 500→750)
 */
'use strict';

const EXTRA_FACTS_2 = {
    Science: [
        ["Sunlight takes about 8 minutes and 20 seconds to reach Earth.", "NASA"],
        ["A single human hair can support up to 100 grams of weight.", "Materials Science"],
        ["There are more ways to arrange a deck of cards than atoms on Earth.", "Combinatorics"],
        ["Mercury and Venus are the only planets with no moons.", "NASA"],
        ["The speed of sound is about 767 mph at sea level.", "Physics"],
        ["Liquid nitrogen boils at −196°C.", "Chemistry"],
        ["Antimatter is the most expensive substance — about $62.5 trillion per gram.", "CERN"],
        ["A cubic inch of bone can bear a load of 19,000 pounds.", "Biomechanics"],
        ["The Earth receives about 430 quintillion joules of solar energy per hour.", "DOE"],
        ["Graphene is so thin that 3 million sheets stacked would be just 1mm thick.", "Materials Science"],
        ["Plasma is the most common state of matter in the universe, not solid.", "Physics"],
        ["The pH of pure water changes with temperature.", "Chemistry"],
        ["Radio waves travel at the speed of light.", "Electromagnetic Theory"],
        ["A teaspoon of water contains about 1.67 sextillion molecules.", "Chemistry"],
        ["The Moon is slowly drifting away from Earth at 3.8 cm per year.", "NASA"],
        ["Superconductors have zero electrical resistance below critical temperature.", "Physics"],
        ["The Doppler effect works for both sound and light.", "Physics"],
        ["Fullerenes are soccer-ball-shaped carbon molecules discovered in 1985.", "Chemistry"],
        ["Dark matter makes up about 27% of the universe.", "Cosmology"],
        ["The double-slit experiment proves light behaves as both wave and particle.", "Quantum Mechanics"],
        ["Piezoelectric crystals generate electricity when squeezed.", "Materials Science"],
        ["The half-life of carbon-14 is approximately 5,730 years.", "Nuclear Physics"],
        ["Ferrofluid is a liquid that becomes magnetized in the presence of a magnetic field.", "Physics"],
        ["Maxwell's equations unified electricity and magnetism in 1865.", "Physics"],
        ["Photosynthesis converts about 1-2% of sunlight into chemical energy.", "Biology"]
    ],
    History: [
        ["The Pony Express only operated for 18 months before the telegraph replaced it.", "Postal History"],
        ["The first known use of the word 'computer' was in 1613 — it referred to a person.", "Oxford English Dictionary"],
        ["Ancient Hawaiians used to surf on 15-foot wooden boards weighing up to 200 pounds.", "Cultural History"],
        ["The first commercial flight occurred in 1914 — Tampa to St. Petersburg, Florida.", "Aviation"],
        ["In 1811, nearly half of all banknotes in circulation in the US were counterfeit.", "US Treasury"],
        ["The Code of Hammurabi from 1754 BC is one of the oldest written laws.", "Mesopotamian History"],
        ["The first crossword puzzle was published in the New York World in 1913.", "Publishing"],
        ["Tulip bulbs were once more valuable than houses in 17th century Netherlands.", "Tulip Mania"],
        ["The first person to circumnavigate the globe solo was Joshua Slocum in 1898.", "Maritime History"],
        ["Alexander the Great named over 70 cities after himself — and one after his horse.", "Ancient History"],
        ["The Olympic flame tradition was actually started by the Nazis for the 1936 Berlin Games.", "Olympic History"],
        ["The first skyscraper was the Home Insurance Building in Chicago, built in 1885.", "Architecture"],
        ["The Spanish flu infected about one-third of the world's population in 1918.", "Medical History"],
        ["Samurai warriors tested new swords on condemned criminals.", "Japanese History"],
        ["The pyramids of Giza were originally covered in smooth white limestone.", "Egyptology"],
        ["The printing press led to a 80% drop in book prices within 50 years.", "Gutenberg"],
        ["King Henry VIII had six wives — and he had two of them executed.", "English History"],
        ["The first ever speeding ticket was issued in 1896 for going 8 mph.", "Transport History"],
        ["Ancient Greek athletes competed completely naked in the original Olympics.", "Olympic History"],
        ["The Roman army could build a temporary fort every single night while marching.", "Military History"],
        ["The Dead Sea Scrolls were discovered by a shepherd looking for a lost goat.", "Archaeology"],
        ["Morse code's SOS doesn't stand for anything — it was chosen for simplicity.", "Communication"],
        ["The Aztec capital Tenochtitlan had a larger population than London when Cortés arrived.", "Latin American History"],
        ["The first known copyright law was the Statute of Anne, passed in 1710.", "Legal History"],
        ["Pigeons were used to deliver results of the ancient Olympic Games to other cities.", "Ancient Greece"]
    ],
    Nature: [
        ["The Amazon basin contains one-fifth of the world's fresh water.", "USGS"],
        ["Wildfires can create their own weather systems including lightning and tornadoes.", "Meteorology"],
        ["A single mature tree can produce enough oxygen for two people per year.", "Forestry"],
        ["The world's largest cave, Son Doong in Vietnam, has its own weather system.", "Speleology"],
        ["Butterfly wings are actually transparent — colors come from light reflection.", "Entomology"],
        ["Lake Hillier in Australia is naturally bright pink and scientists aren't sure why.", "Marine Biology"],
        ["The deepest roots ever recorded belong to a South African fig tree — 400 feet deep.", "Botany"],
        ["Monsoon rains in India can dump 35 feet of rain in a season.", "Meteorology"],
        ["Fire whirls can reach temperatures of 2,000°F and spin at over 100 mph.", "NOAA"],
        ["One lightning bolt can generate up to one billion volts of electricity.", "NOAA"],
        ["Soil contains more organisms per handful than people on the planet.", "Ecology"],
        ["The oldest rocks on Earth are about 4 billion years old — found in Canada.", "Geology"],
        ["Frost flowers are ice crystals that form on thin ice in extremely cold conditions.", "Meteorology"],
        ["Bioluminescent bays glow bright blue at night due to dinoflagellates.", "Marine Biology"],
        ["A tornado's path of destruction can exceed one mile wide.", "NOAA"],
        ["The world's tallest tree is a coast redwood named Hyperion — 380 feet tall.", "National Park Service"],
        ["Earthquakes can permanently shorten the length of a day by microseconds.", "NASA"],
        ["The Bermuda Triangle is one of the most heavily traveled shipping lanes in the world.", "Coast Guard"],
        ["Fog harvesting nets can collect drinking water from misty air.", "Water Engineering"],
        ["The Pacific Ring of Fire accounts for about 90% of the world's earthquakes.", "USGS"],
        ["Volcanic soil is among the most fertile on Earth due to mineral content.", "Agriculture"],
        ["Ball lightning is so rare that scientists still debate whether it truly exists.", "Physics"],
        ["The Catatumbo lightning in Venezuela strikes 280 times per hour.", "Meteorology"],
        ["Tectonic plates beneath Iceland are pulling apart at 2.5 cm per year.", "Geology"],
        ["A rainbow is actually a full circle — we only see a semicircle from the ground.", "Optics"]
    ],
    Space: [
        ["The Sun will eventually expand and engulf Mercury, Venus, and possibly Earth.", "Stellar Evolution"],
        ["There are more than 500,000 pieces of space debris tracked orbiting Earth.", "ESA"],
        ["The oldest light we can see is from the cosmic microwave background — 13.8 billion years old.", "Cosmology"],
        ["Jupiter's Great Red Spot is a storm that has raged for over 400 years.", "NASA"],
        ["Neil Armstrong's famous first step was with his left foot.", "NASA"],
        ["The Moon has moonquakes caused by tidal forces from Earth.", "Lunar Science"],
        ["A year on Neptune is 165 Earth years.", "NASA"],
        ["The Kuiper Belt extends from Neptune's orbit to 50 AU from the Sun.", "NASA"],
        ["Astronauts on the ISS see about 16 sunrises and sunsets per day.", "NASA"],
        ["The farthest human-made object from Earth is Voyager 1.", "NASA"],
        ["Mercury's temperature ranges from −180°C at night to 430°C during the day.", "NASA"],
        ["Ganymede, Jupiter's moon, is larger than the planet Mercury.", "NASA"],
        ["Dark energy makes up about 68% of the universe.", "Cosmology"],
        ["The Crab Nebula was created from a supernova observed by Chinese astronomers in 1054 AD.", "Astronomy"],
        ["Light from the Andromeda galaxy takes 2.5 million years to reach us.", "Astronomy"],
        ["The asteroid belt between Mars and Jupiter contains millions of asteroids.", "NASA"],
        ["Pluto's largest moon, Charon, is so large they orbit a point between them.", "NASA"],
        ["A neutron star's density means a matchbox of material would weigh 3 billion tons.", "Astrophysics"],
        ["The first animal in orbit was Laika the dog in 1957.", "Soviet Space Program"],
        ["Triton, Neptune's largest moon, orbits backwards relative to Neptune's rotation.", "NASA"],
        ["There may be a ninth planet far beyond Neptune — Planet Nine.", "Caltech"],
        ["Solar wind travels at about 1 million mph.", "NASA"],
        ["The closest exoplanet to Earth orbits Proxima Centauri — discovered in 2016.", "ESO"],
        ["Apollo astronauts reported that moondust smells like spent gunpowder.", "NASA"],
        ["The event horizon of a black hole is the point of no return for light.", "Astrophysics"]
    ],
    "Human Body": [
        ["The average adult body contains about 206 bones.", "Anatomy"],
        ["Your brain generates about 70,000 thoughts per day.", "Neuroscience"],
        ["The longest bone in the body is the femur (thighbone).", "Anatomy"],
        ["You lose about 50-100 hairs per day naturally.", "Dermatology"],
        ["The entire surface of your skin renews itself every 2-3 weeks.", "Dermatology"],
        ["Taste buds only live for about 10 days before being replaced.", "Physiology"],
        ["The appendix isn't useless — it may serve as a reservoir for gut bacteria.", "Gastroenterology"],
        ["Yawning helps cool down the brain.", "Neuroscience"],
        ["Your fingerprints are fully formed by the time you are 6 months in the womb.", "Embryology"],
        ["The fastest growing nail is on your middle finger.", "Dermatology"],
        ["Hiccups can last for years — the longest recorded case lasted 68 years.", "Guinness"],
        ["The resolution of the human eye is about 576 megapixels.", "Ophthalmology"],
        ["Stomach acid has a pH of about 1.5-3.5 — strong enough to dissolve metal.", "Gastroenterology"],
        ["Your body produces about 3.8 million cells every second.", "Cell Biology"],
        ["Human saliva contains a painkiller called opiorphin, 6x stronger than morphine.", "Pasteur Institute"],
        ["The total length of your circulatory system is about 60,000 miles.", "Cardiology"],
        ["Dead skin cells account for about a billion tons of dust in the atmosphere.", "Environmental Science"],
        ["Humans are the only animals with chins.", "Anthropology"],
        ["Your brain is about 75% water.", "Neuroscience"],
        ["Muscle memory doesn't actually reside in muscles — it's stored in the brain.", "Neuroscience"],
        ["The human body contains about 37.2 trillion cells.", "Cell Biology"],
        ["Babies can breathe and swallow at the same time — adults cannot.", "Physiology"],
        ["The liver performs over 500 different functions.", "Hepatology"],
        ["Earwax is actually a type of sweat.", "Dermatology"],
        ["Your body gives off enough heat in 30 minutes to boil half a gallon of water.", "Thermodynamics"]
    ],
    Animals: [
        ["Parrots name their chicks — each baby gets a unique set of calls.", "Ornithology"],
        ["The box jellyfish has 64 anuses.", "Marine Biology"],
        ["A blue whale's tongue can weigh as much as an elephant.", "Marine Biology"],
        ["Turtles can breathe through their butts.", "Herpetology"],
        ["A flamingo can only eat with its head upside down.", "Ornithology"],
        ["Hammerhead sharks can see 360 degrees — including above and below.", "Marine Biology"],
        ["A group of hedgehogs is called an 'array'.", "Zoology"],
        ["Gorillas can catch human colds and other illnesses.", "Primatology"],
        ["Peacock mantis shrimp can see colors that humans cannot — including ultraviolet.", "Marine Biology"],
        ["Vampire bats share blood meals with hungry roost-mates.", "Zoology"],
        ["A housefly hums in the key of F.", "Entomology"],
        ["Reindeer eyes change color from gold in summer to blue in winter.", "Zoology"],
        ["Whales can hold their breath for up to 90 minutes.", "Marine Biology"],
        ["Dolphins have been observed using sea sponges as tools to protect their snouts.", "Marine Biology"],
        ["The lyrebird can mimic chainsaws, car alarms, and camera shutters.", "Ornithology"],
        ["Kangaroos can't walk backwards.", "Zoology"],
        ["Male penguins propose to females with a pebble.", "Ornithology"],
        ["Squirrels plant thousands of trees annually by forgetting where they buried nuts.", "Ecology"],
        ["A cockroach can hold its breath for 40 minutes.", "Entomology"],
        ["Electric eels can leap out of water to shock predators.", "Ichthyology"],
        ["Girafffe tongues are 18-21 inches long and can clean their own ears.", "Zoology"],
        ["Dolphins stay awake for the first month after birth — and so do their mothers.", "Marine Biology"],
        ["Bees can detect bombs — they can be trained to respond to TNT scent.", "Entomology"],
        ["Honeybees can recognize human faces.", "Insect Cognition"],
        ["The mimic octopus can change both color and texture of its skin.", "Marine Biology"]
    ],
    Technology: [
        ["GPS requires at least 4 satellites to determine your exact position.", "Navigation"],
        ["The first emoji was created in 1999 by Japanese artist Shigetaka Kurita.", "Design"],
        ["About 90% of the world's data was created in the last 2 years.", "IBM"],
        ["The average web page size has grown from 14KB in 1995 to over 2MB today.", "HTTP Archive"],
        ["Quantum computers operate at temperatures colder than outer space.", "IBM"],
        ["The first hard disk, IBM 350, could store only 5 MB of data.", "IBM"],
        ["A virus named 'ILOVEYOU' caused $10 billion in damage in 2000.", "Cybersecurity"],
        ["The term 'debugging' originated when a moth was found in Harvard's Mark II computer.", "Computer History"],
        ["Over 400 million tweets are sent every day.", "Twitter"],
        ["Tesla's Autopilot processes about 2,300 frames per second.", "Tesla"],
        ["The world's first programmable robot was created in 1954.", "Robotics"],
        ["There are approximately 7,000 programming languages in existence.", "IEEE"],
        ["The first online purchase was a Sting CD sold in 1994.", "Ecommerce"],
        ["Li-Fi technology uses light to transmit data 100 times faster than Wi-Fi.", "Communications"],
        ["3D printing was invented in 1983 by Chuck Hull.", "3D Systems"],
        ["The longest-running computer program has been running since 1958.", "Computer Science"],
        ["Deep Blue became the first computer to beat a world chess champion in 1997.", "IBM"],
        ["CAPTCHA stands for 'Completely Automated Public Turing test'.", "Cybersecurity"],
        ["The term 'spam' for junk email comes from a Monty Python sketch.", "Internet Culture"],
        ["5G networks can theoretically reach speeds of 20 Gbps.", "Telecommunications"],
        ["The first banner ad on the internet appeared in 1994 on HotWired.", "Digital Marketing"],
        ["Facial recognition technology can now identify people wearing masks.", "AI"],
        ["A Boeing 787 Dreamliner generates about 0.5 TB of data per flight.", "Aviation"],
        ["GitHub hosts over 200 million code repositories.", "GitHub"],
        ["The average person will spend about 6 years of their life on social media.", "Digital Wellness"]
    ],
    Food: [
        ["Arachibutyrophobia is the fear of peanut butter sticking to the roof of your mouth.", "Psychology"],
        ["It takes about 400 cocoa beans to make one pound of chocolate.", "Food Science"],
        ["An average ear of corn has about 800 kernels in 16 rows.", "Agriculture"],
        ["The most stolen food in the world is cheese.", "Crime Statistics"],
        ["Carrots were originally white, yellow, and purple before being bred orange.", "Agriculture"],
        ["A cucumber is 96% water — making it the most water-rich food.", "Nutrition"],
        ["The origin of the sandwich dates to the Earl of Sandwich in 1762.", "Food History"],
        ["Cashews grow on the bottom of cashew apples.", "Botany"],
        ["Durian fruit is banned on public transport in Singapore and Thailand.", "Food Culture"],
        ["Worcestershire sauce is made from dissolved anchovies.", "Food Production"],
        ["The average American consumes about 23 pounds of pizza per year.", "USDA"],
        ["Ranch dressing is dyed white — without titanium dioxide it would be pale green.", "Food Science"],
        ["Blueberries are one of the only natural foods that are truly blue.", "Botany"],
        ["Gum takes about 5 years to break down if swallowed — not 7.", "Gastroenterology"],
        ["Balsamic vinegar of Modena must be aged for at least 12 years.", "Italian Food Standards"],
        ["A banana is naturally slightly radioactive due to potassium-40.", "Physics"],
        ["The world consumes about 2.25 billion cups of coffee every day.", "International Coffee Org"],
        ["Tomatoes were considered poisonous in Europe until the 18th century.", "Food History"],
        ["Ground cinnamon is often cassia bark, not true Ceylon cinnamon.", "Spice Trade"],
        ["A jar of Nutella is sold every 2.5 seconds somewhere in the world.", "Ferrero"],
        ["Lettuce is a member of the sunflower family.", "Botany"],
        ["Black pepper was once so valuable it was used as currency.", "Spice Trade"],
        ["Cranberries bounce when they're ripe — farmers test quality this way.", "Agriculture"],
        ["Nori seaweed has more vitamin C than oranges.", "Nutrition"],
        ["A single tomato plant can produce 200 tomatoes in a season.", "Agriculture"]
    ],
    Geography: [
        ["The Pacific Ocean covers more area than all the land on Earth combined.", "NOAA"],
        ["The shortest distance between Russia and the US is just 2.4 miles.", "Geography"],
        ["Ethiopia follows a calendar that is 7 years behind the Gregorian calendar.", "Culture"],
        ["The Sargasso Sea is the only sea with no coastline — it's bounded by currents.", "Oceanography"],
        ["There's a town in Norway called Hell — it freezes over every winter.", "Geography"],
        ["The border between India and Bangladesh has enclaves within enclaves.", "Political Geography"],
        ["The Aral Sea in Central Asia has shrunk to 10% of its original size.", "Environmental Science"],
        ["Mongolia is the most sparsely populated country with 2 people per sq km.", "Demographics"],
        ["The Zambezi River is home to the world's largest waterfall by volume — Victoria Falls.", "Geography"],
        ["Iceland grows about 5 cm wider every year due to tectonic plates.", "Geology"],
        ["Singapore is one of only 3 surviving city-states in the world.", "Political Geography"],
        ["The Richat Structure in Mauritania looks like a giant eye from space.", "Geology"],
        ["Lake Titicaca is the highest navigable lake in the world at 12,500 feet.", "Geography"],
        ["New Zealand was the last habitable land mass to be settled by humans.", "History"],
        ["The tallest mountain from base to peak is Mauna Kea — taller than Everest underwater.", "Geography"],
        ["Nauru is the world's smallest island nation at just 8 square miles.", "Geography"],
        ["The International Date Line zigzags to avoid splitting countries between two days.", "Geography"],
        ["Bhutan is the world's only carbon-negative country.", "Climate"],
        ["The Mohorovičić discontinuity marks the boundary between Earth's crust and mantle.", "Geology"],
        ["Finland has more saunas than cars.", "Culture"],
        ["The Strait of Malacca is the world's busiest shipping lane.", "Maritime"],
        ["Colombia is the only South American country with coastlines on both oceans.", "Geography"],
        ["Sudan has more pyramids than Egypt.", "Archaeology"],
        ["The Maldives is the flattest country — highest point is just 7.8 feet.", "Geography"],
        ["The Mariana Trench is so deep that Mount Everest could fit inside with room to spare.", "Oceanography"]
    ],
    "Pop Culture": [
        ["The phrase 'OK' may be the most widely understood word in the world.", "Linguistics"],
        ["The first webcam was invented to monitor a coffee pot at Cambridge.", "Computer History"],
        ["'Jeopardy!' has been on the air since 1964.", "Television"],
        ["The longest-running animated TV show is The Simpsons since 1989.", "Television"],
        ["The term 'selfie' was first used in an Australian online forum in 2002.", "Internet Culture"],
        ["Rubik's Cube has 43 quintillion possible configurations.", "Mathematics"],
        ["The Big Mac Index is used by economists to compare purchasing power.", "The Economist"],
        ["The first ever music video played on MTV was 'Video Killed the Radio Star'.", "MTV"],
        ["Spotify has over 100 million tracks available for streaming.", "Spotify"],
        ["Wordle was bought by the New York Times for over $1 million.", "Gaming"],
        ["The first 3D movie was shown in 1922 — 'The Power of Love'.", "Cinema"],
        ["The world record for most T-shirts worn at once is 260.", "Guinness"],
        ["The Guinness Book of Records was originally created to settle pub arguments.", "Guinness"],
        ["Pokémon is the highest-grossing media franchise ever at $100+ billion.", "Entertainment"],
        ["Alice in Wonderland was banned in China because animals shouldn't talk.", "Censorship"],
        ["Scrabble was originally called 'Lexiko' and then 'Criss-Crosswords'.", "Games"],
        ["The first GIF ever created was of a rotating globe on CompuServe in 1987.", "Internet History"],
        ["Angry Birds has been downloaded over 4 billion times.", "Gaming"],
        ["The most expensive domain name ever sold was cars.com for $872 million.", "Internet"],
        ["Instagram's first photo was of a dog near a taco stand.", "Social Media"],
        ["The most-liked photo on Instagram is a picture of an egg.", "Social Media"],
        ["Reddit has more monthly active users than Twitter.", "Social Media"],
        ["The Oxford comma debate has been going on for over 100 years.", "Grammar"],
        ["The world record for binge-watching TV is 94 hours.", "Guinness"],
        ["TikTok was the most downloaded app worldwide in 2020, 2021, and 2022.", "App Analytics"]
    ]
};

/* istanbul ignore next */
if (typeof module !== 'undefined') {
    module.exports = { EXTRA_FACTS_2 };
}
