/**
 * Additional facts — batch 4 (25 more per category, 750→1000)
 */
'use strict';

const EXTRA_FACTS_3 = {
    Science: [
        ["Neutrinos can pass through an entire planet without hitting a single atom.", "Particle Physics"],
        ["The loudest sound on Earth was the eruption of Krakatoa in 1883 — heard 3,000 miles away.", "Geophysics"],
        ["Entropy always increases in a closed system — the second law of thermodynamics.", "Physics"],
        ["The Casimir effect proves that empty space isn't truly empty.", "Quantum Field Theory"],
        ["Fluorescent lights work by exciting mercury vapor to produce ultraviolet light.", "Physics"],
        ["A bolt of lightning is five times hotter than the surface of the Sun.", "NOAA"],
        ["Buckminsterfullerene (C60) is shaped like a soccer ball at the molecular level.", "Chemistry"],
        ["Quantum tunneling allows particles to pass through barriers they shouldn't be able to.", "Quantum Mechanics"],
        ["Human-made elements above 118 on the periodic table are theoretically possible.", "Nuclear Physics"],
        ["Metamaterials can bend light around objects, potentially enabling invisibility.", "Optics"],
        ["The observable universe contains about 2 trillion galaxies.", "NASA"],
        ["Bose-Einstein condensate is a fifth state of matter created near absolute zero.", "Physics"],
        ["Penicillin was discovered by accident when mold contaminated a petri dish.", "Alexander Fleming"],
        ["The uncertainty principle means you can never know both position and momentum exactly.", "Heisenberg"],
        ["Volcanic lightning occurs when ash particles collide and generate static electricity.", "Geophysics"],
        ["Magnetars are neutron stars with magnetic fields a quadrillion times Earth's.", "Astrophysics"],
        ["The photoelectric effect proved light can behave as particles — earning Einstein the Nobel.", "Physics"],
        ["Superfluids can flow uphill and through molecularly thin cracks.", "Low Temperature Physics"],
        ["There are 118 confirmed elements on the periodic table.", "IUPAC"],
        ["A googolplex is 10 raised to the power of a googol.", "Mathematics"],
        ["Cosmic rays from deep space constantly bombard Earth.", "Astrophysics"],
        ["The twin paradox in relativity means space travelers age slower.", "Special Relativity"],
        ["Graphene can conduct electricity better than copper.", "Materials Science"],
        ["The placebo effect works even when patients know they're taking a placebo.", "Medical Research"],
        ["Tidal forces from the Moon generate about 3.7 terawatts of energy.", "Geophysics"]
    ],
    History: [
        ["The first vending machine dispensed holy water in ancient Egypt around 215 BC.", "Hero of Alexandria"],
        ["Marie Curie's notebooks are still radioactive and kept in lead-lined boxes.", "Science History"],
        ["The first photograph ever taken required an 8-hour exposure.", "Niépce, 1826"],
        ["The Library of Congress is the largest library in the world with 170 million items.", "LOC"],
        ["The Berlin Wall fell in 1989 partly due to a miscommunicated press conference.", "German History"],
        ["Ancient Chinese soldiers used to strap firecrackers to arrows.", "Military History"],
        ["The first newspaper was published in Germany in 1605.", "Media History"],
        ["Cleopatra was actually Greek, not Egyptian.", "Ancient History"],
        ["The first successful blood transfusion was performed in 1665 — between two dogs.", "Medical History"],
        ["Viking longships could sail in water as shallow as 3 feet.", "Maritime History"],
        ["The Incas had no written language but used knotted strings called quipus.", "Latin American History"],
        ["The first modern census was conducted by the Romans.", "Governance"],
        ["Ada Lovelace wrote the first algorithm intended for machine processing.", "Computer History"],
        ["The Great Fire of London helped end the bubonic plague in the city.", "English History"],
        ["The first contact lenses were made of blown glass in 1888.", "Optical History"],
        ["Genghis Khan's empire was the largest contiguous land empire in history.", "World History"],
        ["The construction of the Panama Canal cost about 25,000 workers' lives.", "Engineering"],
        ["The Bayeux Tapestry is actually an embroidery, not a tapestry.", "Art History"],
        ["The French gifted the Statue of Liberty to the US in 350 separate pieces.", "American History"],
        ["The first underwater photograph was taken in 1856.", "Photography"],
        ["The zipper was invented in 1893 but didn't become popular until the 1930s.", "Invention"],
        ["The Silk Road stretched over 4,000 miles connecting East to West.", "Trade History"],
        ["The ancient city of Petra was carved directly into red sandstone cliffs.", "Archaeology"],
        ["The first scheduled airline flight cost $5 — equivalent to about $150 today.", "Aviation"],
        ["The Rosetta Stone was discovered by French soldiers in 1799.", "Egyptology"]
    ],
    Nature: [
        ["The Amazon River discharges more water than the next 7 largest rivers combined.", "Hydrology"],
        ["Dandelion seeds can travel up to 100 km carried by the wind.", "Botany"],
        ["Geysers exist on only 6 continents — Antarctica has none.", "Geology"],
        ["The Sundarbans mangrove forest is the largest in the world at 3,860 sq mi.", "UNESCO"],
        ["A single thunderstorm can produce over 100 million gallons of rainwater.", "NOAA"],
        ["Glaciers hold about 69% of the world's fresh water.", "USGS"],
        ["The Svalbard Global Seed Vault stores 1.1 million seed samples from around the world.", "Agriculture"],
        ["Lava can flow at speeds up to 40 mph on steep slopes.", "Volcanology"],
        ["The world's largest desert is actually Antarctica — it's a cold desert.", "Geography"],
        ["Some deep-sea fish produce their own light through bioluminescence.", "Marine Biology"],
        ["Moss can survive in extreme environments including Arctic temperatures.", "Bryology"],
        ["The world's largest single flower is Rafflesia arnoldii at 3 feet across.", "Botany"],
        ["Petrified Forest in Arizona contains 225 million-year-old trees turned to stone.", "Geology"],
        ["Tsunamis can travel across the ocean at 500+ mph.", "Seismology"],
        ["The oldest water on Earth was found 2 miles underground — 2 billion years old.", "Geology"],
        ["Bacteria can survive in the stratosphere at altitudes of 25 miles.", "Microbiology"],
        ["The world's deepest lake is Lake Baikal at 5,387 feet deep.", "Limnology"],
        ["Fulgurites are glass tubes formed when lightning strikes sand.", "Geology"],
        ["A single colony of aspen trees called Pando covers 106 acres.", "Ecology"],
        ["Trade winds blow consistently from east to west near the equator.", "Meteorology"],
        ["Earth's atmosphere extends about 6,200 miles from the surface.", "Atmospheric Science"],
        ["The tallest known tsunami wave was 1,720 feet high in Lituya Bay, Alaska.", "USGS"],
        ["Permafrost contains twice as much carbon as the atmosphere.", "Climate Science"],
        ["The Hawaiian Islands were formed by a hotspot in the Earth's mantle.", "Geology"],
        ["Sinkholes form when underground limestone is dissolved by acidic rainwater.", "Karst Geology"]
    ],
    Space: [
        ["Enceladus, Saturn's moon, has geysers that shoot water ice into space.", "Cassini Mission"],
        ["The total mass of the asteroid belt is less than 4% of the Moon's mass.", "NASA"],
        ["White dwarfs are so dense that a teaspoon would weigh 5 tons.", "Stellar Physics"],
        ["The universe is expanding faster than the speed of light at its edges.", "Cosmology"],
        ["Mars' atmosphere is 96% carbon dioxide.", "NASA"],
        ["The Kepler telescope discovered over 2,600 confirmed exoplanets.", "NASA"],
        ["Olympus Mons on Mars has a caldera large enough to contain an entire city.", "Planetary Science"],
        ["Cosmic microwave background radiation has a temperature of 2.725 Kelvin.", "COBE"],
        ["Binary star systems are more common than single stars like our Sun.", "Stellar Astronomy"],
        ["A quasar can outshine an entire galaxy containing billions of stars.", "Astrophysics"],
        ["The speed of light in a vacuum is the universal speed limit.", "Special Relativity"],
        ["Saturn's rings are made mostly of ice particles and rocky debris.", "NASA"],
        ["The Apollo missions brought back 842 pounds of Moon rocks.", "NASA"],
        ["Pulsars are rotating neutron stars that emit beams of electromagnetic radiation.", "Astrophysics"],
        ["The Boomerang Nebula is the coldest known place in the universe at −272°C.", "Astronomy"],
        ["Our galaxy orbits the center of the local galaxy cluster.", "Cosmology"],
        ["The Sun converts about 600 million tons of hydrogen into helium every second.", "Solar Physics"],
        ["There may be billions of rogue planets wandering between stars.", "Astronomy"],
        ["The space between galaxies is not truly empty — it contains sparse hydrogen.", "Cosmology"],
        ["The first spacewalk was performed by Alexei Leonov in 1965.", "Soviet Space Program"],
        ["Gravitational waves were first detected in 2015 by LIGO.", "Physics"],
        ["The habitable zone is the distance from a star where liquid water could exist.", "Astrobiology"],
        ["A magnetar's magnetic field could erase a credit card from 100,000 miles away.", "Astrophysics"],
        ["The Sun orbits the center of the Milky Way at 515,000 mph.", "Astronomy"],
        ["Supermassive black holes at galaxy centers can contain billions of solar masses.", "Astrophysics"]
    ],
    "Human Body": [
        ["Only about 10% of the cells in your body are human — the rest are microbes.", "Microbiome Project"],
        ["The average person spends about 2 weeks of their lifetime waiting at traffic lights.", "Statistics"],
        ["Your brain's storage capacity is about 2.5 petabytes.", "Neuroscience"],
        ["Synesthesia causes some people to see colors when hearing music.", "Neurology"],
        ["Humans can detect sweetness in a solution of 1 part sugar in 200 parts water.", "Taste Research"],
        ["The platysma is a muscle that runs from your jaw to your shoulders.", "Anatomy"],
        ["Your body contains enough phosphorus to make about 2,200 match heads.", "Chemistry"],
        ["REM sleep is when most vivid dreaming occurs — your eyes actually move rapidly.", "Sleep Science"],
        ["The hand contains 27 bones — more than any other body part.", "Anatomy"],
        ["Oxytocin, the 'love hormone', is released during hugging, touching, and singing.", "Endocrinology"],
        ["Your sense of smell is closely linked to memory because of the olfactory bulb's location.", "Neuroscience"],
        ["Scar tissue has no sweat glands or hair follicles.", "Dermatology"],
        ["The human body contains about 0.2% potassium by weight.", "Biochemistry"],
        ["Mirror neurons fire both when you perform an action and when you see someone else do it.", "Neuroscience"],
        ["Charles Osborne had hiccups for 68 years — from 1922 to 1990.", "Medical Records"],
        ["Fingernails grow about 3.5 mm per month — toenails about 1.6 mm.", "Dermatology"],
        ["The average person takes about 20,000 breaths per day.", "Pulmonology"],
        ["Melanin determines both skin and hair color.", "Genetics"],
        ["Your body generates about 100 watts of power at rest — like a light bulb.", "Biophysics"],
        ["The Achilles tendon is the strongest tendon in the human body.", "Anatomy"],
        ["Night vision takes about 20-30 minutes for your eyes to fully adjust.", "Ophthalmology"],
        ["The pace of your heartbeat changes to mimic the music you listen to.", "Cardiology"],
        ["Red blood cells live about 120 days before being replaced.", "Hematology"],
        ["Humans have fewer genes than a grape — about 20,000 vs 30,000.", "Genetics"],
        ["Your gut contains about 100 trillion bacteria — more than cells in your body.", "Microbiome"]
    ],
    Animals: [
        ["Dolphins can learn to recognize themselves in a mirror.", "Cognitive Science"],
        ["A group of crows solving a problem together is called a 'murder mystery'.", "Folklore"],
        ["Axolotls can regrow not just limbs but also parts of their heart and brain.", "Regenerative Biology"],
        ["Tardigrades can survive temperatures from −272°C to 150°C.", "Extremophile Biology"],
        ["The sailfish is the fastest fish, reaching speeds of 68 mph.", "Marine Biology"],
        ["Cephalopods like squid can edit their own RNA.", "Genetics"],
        ["An albatross can fly for years without landing.", "Ornithology"],
        ["The bombardier beetle sprays boiling chemical spray at predators.", "Entomology"],
        ["Some species of fish can change sex depending on social conditions.", "Marine Biology"],
        ["A snapping turtle's bite force is about 1,000 pounds per square inch.", "Herpetology"],
        ["African wild dogs vote on pack decisions by sneezing.", "Animal Behavior"],
        ["The woodpecker's tongue wraps around the back of its skull.", "Ornithology"],
        ["Cleaner wrasse fish can pass the mirror test for self-recognition.", "Marine Biology"],
        ["Penguins can drink salt water — special glands filter out the salt.", "Marine Biology"],
        ["The basilisk lizard can run on water for short distances.", "Herpetology"],
        ["Some frogs can freeze solid and then thaw out alive.", "Cryobiology"],
        ["Army ants can form living bridges with their own bodies.", "Entomology"],
        ["Narwhals' tusks are actually elongated teeth that grow in a spiral.", "Marine Biology"],
        ["Corvids (crows and ravens) use tools and can plan for the future.", "Animal Cognition"],
        ["The fastest land animal is the cheetah at 70 mph.", "Zoology"],
        ["Leaf-cutter ants farm fungus underground — the only non-human farmers.", "Entomology"],
        ["The golden poison frog has enough toxin to kill 10 grown men.", "Toxicology"],
        ["Sperm whales sleep vertically, bobbing at the surface.", "Marine Biology"],
        ["Mole rats are virtually immune to cancer.", "Biology"],
        ["Some butterflies migrate over 3,000 miles — like the Monarch.", "Entomology"]
    ],
    Technology: [
        ["The first website went live on August 6, 1991.", "Tim Berners-Lee"],
        ["Blockchain technology was originally described in 1991 — 17 years before Bitcoin.", "Computer Science"],
        ["The Apollo 11 guidance computer had only 74 KB of memory.", "NASA"],
        ["Over 570 new websites are created every minute.", "Internet Live Stats"],
        ["The first smartphone was the IBM Simon, released in 1994.", "IBM"],
        ["A self-driving car generates about 100 GB of data per second.", "Automotive"],
        ["The first YouTube upload was titled 'Me at the zoo' — only 19 seconds long.", "YouTube"],
        ["There are more than 2 billion gamers worldwide.", "Newzoo"],
        ["Brain-computer interfaces can now allow paralyzed patients to type with thoughts.", "Neuralink"],
        ["Stuxnet was the first known cyberweapon — it damaged Iranian nuclear centrifuges.", "Cybersecurity"],
        ["The first hard drive to hold 1 GB cost $40,000 and weighed 550 lbs in 1980.", "IBM"],
        ["The first GIF ever created was of a plane by Steve Wilhite in 1987.", "Internet History"],
        ["Optical fibers can carry data at 99.7% the speed of light.", "Telecommunications"],
        ["The most downloaded app of all time is Facebook.", "App Annie"],
        ["AlphaGo defeated the world champion at Go in 2016 — considered impossible.", "DeepMind"],
        ["Voice assistants process your speech in the cloud, not on your device.", "AI"],
        ["The first ATM was installed in London in 1967.", "Banking"],
        ["Solid-state batteries could double the range of electric vehicles.", "Energy"],
        ["The world's fastest internet speed achieved was 319 terabits per second.", "NICT Japan"],
        ["About 4.6 billion people actively use social media.", "Statista"],
        ["USB-C can deliver up to 240 watts of power.", "USB Implementers Forum"],
        ["The first virtual reality headset was created in 1968.", "Ivan Sutherland"],
        ["Error 404 is named after room 404 at CERN where the web was developed.", "Internet Lore"],
        ["Over 300 billion emails are sent worldwide every day.", "Statista"],
        ["The average data center uses as much electricity as 25,000 households.", "DOE"]
    ],
    Food: [
        ["Saffron requires 75,000 flowers to produce one pound of spice.", "Spice Trade"],
        ["Maple syrup was first collected by Indigenous peoples of North America.", "Food History"],
        ["The world's largest pizza was 13,580 sq ft — made in Rome.", "Guinness"],
        ["Wasabi you eat at most restaurants is actually dyed horseradish.", "Food Industry"],
        ["A single fast-food meal can contain more sodium than you need in a day.", "Nutrition"],
        ["Vanilla extract contains at least 35% alcohol by FDA standards.", "FDA"],
        ["The human tongue can detect umami — the fifth basic taste.", "Taste Science"],
        ["An avocado has more potassium than a banana.", "Nutrition"],
        ["The oldest wine cellar is in the ruins of a Canaanite palace — 3,700 years old.", "Archaeology"],
        ["Margherita pizza was named after Queen Margherita of Italy in 1889.", "Food History"],
        ["Quinoa is technically a seed, not a grain.", "Botany"],
        ["Oysters can change their gender back and forth throughout their lives.", "Marine Biology"],
        ["The world's most expensive spice is saffron at $500-5,000 per pound.", "Spice Trade"],
        ["Coffee beans are the pit of a cherry-like fruit called a coffee cherry.", "Botany"],
        ["Eating celery burns more calories than the celery itself contains.", "Nutrition Myth"],
        ["Swiss cheese has holes because of CO2 released by bacteria during aging.", "Food Science"],
        ["The average person eats about 35 tons of food in a lifetime.", "Statistics"],
        ["Pistachios can spontaneously combust when shipped in large quantities.", "Food Safety"],
        ["Mozzarella di Bufala is made from water buffalo milk, not cow milk.", "Italian Food"],
        ["Fish sauce was a staple condiment in ancient Rome called garum.", "Roman Cuisine"],
        ["Bell peppers have more vitamin C per gram than oranges.", "Nutrition"],
        ["The world's oldest known recipe book is 'De Re Coquinaria' from 1st century AD.", "Roman History"],
        ["Truffle hunters use pigs or trained dogs because truffles grow underground.", "Agriculture"],
        ["Instant noodles were invented by Momofuku Ando in 1958.", "Food History"],
        ["A single mature apple tree can produce 800 pounds of fruit per year.", "Agriculture"]
    ],
    Geography: [
        ["The Andes is the longest continental mountain range at 4,350 miles.", "Geography"],
        ["There are 195 countries recognized by the United Nations.", "UN"],
        ["The River Thames is technically a tidal river influenced by the North Sea.", "Hydrology"],
        ["Mount Kilimanjaro is the highest free-standing mountain in the world.", "Geography"],
        ["The Great Rift Valley extends 4,000 miles from Syria to Mozambique.", "Geology"],
        ["The Ganges River is considered sacred by over 1 billion Hindus.", "Culture"],
        ["The Ross Ice Shelf in Antarctica is about the size of France.", "Glaciology"],
        ["The Amazon rainforest spans 9 countries.", "Geography"],
        ["The deepest cave in the world is Veryovkina Cave in Georgia at 7,257 feet.", "Speleology"],
        ["Easter Island is one of the most remote inhabited islands — 2,180 miles from Chile.", "Geography"],
        ["The Grand Canyon is about 277 miles long and up to 18 miles wide.", "National Park Service"],
        ["Kenya and Ethiopia share a border that follows no natural boundary.", "Political Geography"],
        ["The world's saltiest lake is Don Juan Pond in Antarctica.", "Limnology"],
        ["Cuba is the largest island in the Caribbean.", "Geography"],
        ["The Suez Canal saves ships a 7,000-mile journey around Africa.", "Engineering"],
        ["Lake Victoria is the second-largest freshwater lake by surface area.", "Geography"],
        ["New Zealand's Milford Sound receives about 268 inches of rain per year.", "Meteorology"],
        ["The country of Kiribati spans all four hemispheres.", "Geography"],
        ["The Ogallala Aquifer under the US Great Plains covers 174,000 square miles.", "USGS"],
        ["The Namib Desert in Africa is the oldest desert at 55-80 million years.", "Geology"],
        ["Only 3 countries use red, white, and blue and don't have stripes: Nepal, Israel, and Georgia.", "Vexillology"],
        ["The largest salt flat is Salar de Uyuni in Bolivia at 4,086 square miles.", "Geography"],
        ["The Strait of Gibraltar is only 8.9 miles wide at its narrowest point.", "Geography"],
        ["Madagascar split from India about 88 million years ago.", "Plate Tectonics"],
        ["The highest capital city is La Paz, Bolivia, at 11,975 feet above sea level.", "Geography"]
    ],
    "Pop Culture": [
        ["The first email spam was sent in 1978 to 400 people on ARPANET.", "Internet History"],
        ["Pac-Man was originally called Puck Man — changed to avoid vandalism.", "Gaming"],
        ["The most expensive movie ever made was Pirates of the Caribbean: On Stranger Tides.", "Film"],
        ["The Marvel character Deadpool is aware he's a comic book character.", "Comics"],
        ["The longest-running Broadway show is The Phantom of the Opera.", "Theater"],
        ["The world's most translated book after the Bible is The Little Prince.", "Publishing"],
        ["League of Legends has over 100 million active monthly players.", "Gaming"],
        ["The first emoticon was :-) used by Scott Fahlman in 1982.", "Internet Culture"],
        ["Baby Shark is the most-viewed YouTube video ever with 14+ billion views.", "YouTube"],
        ["The first arcade video game was Computer Space in 1971.", "Gaming"],
        ["Twitch streamers have been watched for over 1 trillion minutes.", "Twitch"],
        ["Friends was originally titled 'Insomnia Café'.", "Television"],
        ["The PlayStation 2 is the best-selling console ever at 155 million units.", "Gaming"],
        ["The original Star Wars trilogy was almost called 'Adventures of Luke Starkiller'.", "Film"],
        ["The first podcast was created by Dave Winer and Adam Curry in 2004.", "Media"],
        ["Wikipedia has over 60 million articles across 300+ languages.", "Wikipedia"],
        ["The most expensive painting ever sold was 'Salvator Mundi' for $450 million.", "Art"],
        ["The term 'going viral' became popular in the mid-2000s with YouTube.", "Internet Culture"],
        ["SpongeBob SquarePants was created by a marine science educator.", "Television"],
        ["The average Netflix user watches about 1.5 hours per day.", "Netflix"],
        ["Minecraft has sold over 300 million copies worldwide.", "Gaming"],
        ["The first reality TV show was 'An American Family' in 1973.", "Television"],
        ["The world record for most Rubik's Cube solves in 24 hours is over 6,000.", "Guinness"],
        ["LinkedIn was founded in 2002 — before Facebook, YouTube, and Twitter.", "Social Media"],
        ["The phrase 'break the internet' became a meme after Kim Kardashian's Paper cover.", "Pop Culture"]
    ]
};

/* istanbul ignore next */
if (typeof module !== 'undefined') {
    module.exports = { EXTRA_FACTS_3 };
}
