import os
import json

data = {
    "prompts-directory": [
        {"id": "chatgpt-copywriting", "name": "ChatGPT Copywriting Master", "description": "High-conversion sales copy prompts for SaaS and E-commerce.", "category": "Marketing", "model": "ChatGPT"},
        {"id": "midjourney-v6-cinematic", "name": "Midjourney Cinematic Lighting", "description": "Prompts for ultra-realistic cinematic photography.", "category": "Design", "model": "Midjourney"},
        {"id": "sdxl-anime-style", "name": "SDXL Anime Master", "description": "Highly detailed anime style prompts for Stable Diffusion XL.", "category": "Art", "model": "Stable Diffusion"},
        {"id": "claude-code-architect", "name": "Claude Coding Assistant", "description": "Deep architecture and refactoring prompts for Claude 3.5.", "category": "Development", "model": "Claude"},
        {"id": "prompt-engineering-guide", "name": "Chain-of-Thought Master", "description": "Prompts for complex logical reasoning and multi-step tasks.", "category": "Education", "model": "General"},
        {"id": "dalle3-flat-illustration", "name": "DALL-E 3 Flat Illustration", "description": "Clean, colorful flat design illustrations for web headers.", "category": "Design", "model": "DALL-E 3"},
        {"id": "chatgpt-python-debug", "name": "Python Debugger Pro", "description": "Specific prompts for finding race conditions and memory leaks.", "category": "Development", "model": "ChatGPT"},
        {"id": "midjourney-logo-design", "name": "Minimalist Logo Prompt", "description": "Vector-style minimalist corporate logo prompts.", "category": "Branding", "model": "Midjourney"},
        {"id": "claude-legal-analyzer", "name": "Legal Document Review", "description": "Prompts for summarizing T&C and identifying red flags.", "category": "Productivity", "model": "Claude"},
        {"id": "chatgpt-language-tutor", "name": "Personal Language Tutor", "description": "Immersion-style conversation prompts for language learning.", "category": "Education", "model": "ChatGPT"},
        {"id": "midjourney-architecture", "name": "Modern Interior Design", "description": "Prompts for photorealistic interior architecture renders.", "category": "Design", "model": "Midjourney"},
        {"id": "sd-ui-ux-mockups", "name": "UI/UX Layout Generator", "description": "Interface layout and wireframe inspiration prompts.", "category": "Design", "model": "Stable Diffusion"},
        {"id": "chatgpt-seo-optimizer", "name": "SEO Keyword Strategist", "description": "Prompts for generating semantic keywords and content clusters.", "category": "Marketing", "model": "ChatGPT"},
        {"id": "claude-creative-writer", "name": "Creative Fiction Writing", "description": "Detailed world-building and character development prompts.", "category": "Writing", "model": "Claude"},
        {"id": "midjourney-fashion", "name": "Avant-Garde Fashion Design", "description": "High-fashion concept photography prompts.", "category": "Design", "model": "Midjourney"},
        {"id": "sd-textile-patterns", "name": "Seamless Textile Patterns", "description": "Prompts for creating repeatable fabric and wall patterns.", "category": "Design", "model": "Stable Diffusion"},
        {"id": "chatgpt-excel-formula", "name": "Excel Formula Wizard", "description": "Natural language to complex Excel/Sheets formula prompts.", "category": "Productivity", "model": "ChatGPT"},
        {"id": "claude-research-summary", "name": "Scientific Paper Summarizer", "description": "Prompts for extracting key data points from academic papers.", "category": "Education", "model": "Claude"},
        {"id": "midjourney-poster-art", "name": "1970s Retro Poster Art", "description": "Vintage grainy poster style prompts for aesthetic prints.", "category": "Art", "model": "Midjourney"},
        {"id": "sd-pixel-art", "name": "Game Pixel Art Prompt", "description": "Indie game sprite and landscape pixel art prompts.", "category": "Art", "model": "Stable Diffusion"},
        {"id": "chatgpt-email-cold", "name": "Cold Outreach Cold Email", "description": "High-response rate B2B sales email prompts.", "category": "Marketing", "model": "ChatGPT"},
        {"id": "claude-sql-expert", "name": "SQL Query Optimization", "description": "Prompts for optimizing complex joins and index usage.", "category": "Development", "model": "Claude"},
        {"id": "midjourney-food-photo", "name": "Gourmet Food Photography", "description": "Prompts for high-end restaurant menu photography.", "category": "Marketing", "model": "Midjourney"},
        {"id": "sd-character-sheet", "name": "D&D Character Concept", "description": "Front, side, and back view character design prompts.", "category": "Art", "model": "Stable Diffusion"},
        {"id": "chatgpt-interview-prep", "name": "FAANG Interview Coach", "description": "Mock interview and behavioral question prompts.", "category": "Career", "model": "ChatGPT"},
        {"id": "claude-data-cleaner", "name": "Pandas Data Cleaning", "description": "Prompts for handling missing values and outlier detection.", "category": "Data Science", "model": "Claude"},
        {"id": "midjourney-street-photo", "name": "Cyberpunk Street Photography", "description": "Neon-lit night street photography prompts.", "category": "Art", "model": "Midjourney"},
        {"id": "sd-watercolor-landscape", "name": "Traditional Watercolor Art", "description": "Soft, bleeding watercolor landscape prompts.", "category": "Art", "model": "Stable Diffusion"},
        {"id": "chatgpt-blog-ideas", "name": "Viral Blog Headline Generator", "description": "Click-worthy headline and outline prompts.", "category": "Marketing", "model": "ChatGPT"},
        {"id": "claude-typescript-strict", "name": "Strict TS Type Master", "description": "Prompts for complex generic and utility type definitions.", "category": "Development", "model": "Claude"}
    ],
    "cheatsheets-directory": [
        {"id": "python-standard-lib", "name": "Python Standard Library", "description": "Common methods for os, sys, json, and datetime.", "category": "Programming"},
        {"id": "javascript-es6+", "name": "JavaScript ES6+ Essentials", "description": "Arrow functions, destructuring, and spread operators.", "category": "Programming"},
        {"id": "sql-joins-basics", "name": "SQL Joins & Aggregates", "description": "Visual guide to INNER, LEFT, RIGHT, and FULL joins.", "category": "Database"},
        {"id": "docker-cli-usage", "name": "Docker CLI & Compose", "description": "Commands for managing containers, images, and volumes.", "category": "DevOps"},
        {"id": "git-workflow-pro", "name": "Git Workflow & Branching", "description": "Rebase, cherry-pick, and stash commands explained.", "category": "Development"},
        {"id": "css-grid-layout", "name": "CSS Grid Cheatsheet", "description": "Grid-template properties and alignment cheatsheet.", "category": "Design"},
        {"id": "css-flexbox-guide", "name": "CSS Flexbox One-Pager", "description": "Justify-content, align-items, and flex-grow properties.", "category": "Design"},
        {"id": "markdown-extended", "name": "Markdown & GFM Syntax", "description": "Tables, checklists, and code block formatting.", "category": "Writing"},
        {"id": "vim-shortcuts-all", "name": "Vim Navigation & Editing", "description": "Essential movement and mode switching commands.", "category": "Development"},
        {"id": "linux-terminal-basic", "name": "Linux Terminal Commands", "description": "File manipulation, permissions, and networking basics.", "category": "DevOps"},
        {"id": "regex-tokens-quick", "name": "Regular Expressions Meta", "description": "Lookaheads, anchors, and grouping tokens.", "category": "Programming"},
        {"id": "rust-ownership-rules", "name": "Rust Ownership & Borrowing", "description": "Memory management rules for new Rustaceans.", "category": "Programming"},
        {"id": "go-concurrency-pattern", "name": "Go Routines & Channels", "description": "The 'Don't communicate by sharing memory' guide.", "category": "Programming"},
        {"id": "postgresql-pquery", "name": "PostgreSQL Performance", "description": "EXPLAIN ANALYZE and Indexing strategies.", "category": "Database"},
        {"id": "react-hooks-cheatsheet", "name": "React Hooks & Lifecycle", "description": "useEffect, useMemo, and useCallback examples.", "category": "Frontend"},
        {"id": "tailwind-css-utility", "name": "Tailwind CSS Layout", "description": "Spacing, sizing, and responsive design classes.", "category": "Frontend"},
        {"id": "typescript-types", "name": "TypeScript Type System", "description": "Interfaces, Types, Unions, and Intersections.", "category": "Programming"},
        {"id": "mongodb-aggregation", "name": "MongoDB Aggregation Pipeline", "description": "$match, $group, and $lookup stage guide.", "category": "Database"},
        {"id": "redis-data-types", "name": "Redis Commands & Types", "description": "Working with Strings, Hashes, Lists, and Sets.", "category": "Database"},
        {"id": "aws-cli-essentials", "name": "AWS CLI S3 & EC2", "description": "Top 20 commands for daily AWS management.", "category": "Cloud"},
        {"id": "kubernetes-kubectl", "name": "Kubectl Cheat Sheet", "description": "Context switching, logs, and port-forwarding.", "category": "DevOps"},
        {"id": "bash-scripting", "name": "Bash Scripting Basics", "description": "Loops, conditionals, and exit codes.", "category": "DevOps"},
        {"id": "nginx-config-proxy", "name": "Nginx Reverse Proxy", "description": "Common server blocks and SSL configurations.", "category": "DevOps"},
        {"id": "ansible-playbook", "name": "Ansible Playbook Syntax", "description": "YAML structure, tasks, and handler guide.", "category": "DevOps"},
        {"id": "graphql-schema", "name": "GraphQL Query & Schema", "description": "Mutations, Fragments, and Resolver types.", "category": "API"},
        {"id": "html-semantic-tags", "name": "HTML5 Semantic Elements", "description": "Proper structure for SEO and Accessibility.", "category": "Frontend"},
        {"id": "rest-api-design", "name": "REST API Best Practices", "description": "HTTP methods, status codes, and path naming.", "category": "API"},
        {"id": "chrome-devtools", "name": "Chrome DevTools Shortcuts", "description": "Console, Network, and Performance panel tips.", "category": "Development"},
        {"id": "django-orm-query", "name": "Django ORM Queries", "description": "Filter, exclude, and prefetch_related usage.", "category": "Programming"},
        {"id": "flask-app-structure", "name": "Flask App Patterns", "description": "Blueprints, factories, and context management.", "category": "Programming"}
    ],
    "boilerplates-directory": [
        {"id": "nextjs-saas-starter", "name": "Next.js Zero-Cost SaaS", "description": "Tailwind, Supabase, and Stripe integration.", "category": "Fullstack", "language": "TypeScript"},
        {"id": "vite-react-minimal", "name": "Vite + React (SWC)", "description": "Ultra-fast starter with ESLint and Prettier.", "category": "Frontend", "language": "JavaScript"},
        {"id": "django-rest-boilerplate", "name": "Django REST Framework", "description": "Pre-configured JWT auth and Docker support.", "category": "Backend", "language": "Python"},
        {"id": "flask-htmx-starter", "name": "Flask + HTMX Template", "description": "Modern SPAs without complex JS frameworks.", "category": "Fullstack", "language": "Python"},
        {"id": "rust-wasm-yew", "name": "Rust Yew Web App", "description": "Static site generation with WebAssembly.", "category": "Frontend", "language": "Rust"},
        {"id": "go-gin-api", "name": "Go Gin API Starter", "description": "Restful API with Gorm and Zap logging.", "category": "Backend", "language": "Go"},
        {"id": "laravel-breeze", "name": "Laravel Breeze + Vue", "description": "Modern auth scaffolding with Inertia.js.", "category": "Fullstack", "language": "PHP"},
        {"id": "svelte-kit-auth", "name": "SvelteKit + Auth.js", "description": "Secure starter with social logins in 5 mins.", "category": "Fullstack", "language": "JavaScript"},
        {"id": "astro-starlight", "name": "Astro Starlight Docs", "description": "Beautiful documentation site starter.", "category": "Static Site", "language": "Markdown"},
        {"id": "express-mongo-jwt", "name": "Express + MongoDB Boilerplate", "description": "Node.js API with Passport and Mongoose.", "category": "Backend", "language": "JavaScript"},
        {"id": "fastapi-pydanticv2", "name": "FastAPI + SQLAlchemy", "description": "High-performance API with async support.", "category": "Backend", "language": "Python"},
        {"id": "ruby-on-rails-7", "name": "Rails 7 + Hotwire", "description": "No-build JS frontends with Stimulus.", "category": "Fullstack", "language": "Ruby"},
        {"id": "spring-boot-maven", "name": "Spring Boot 3 + Security", "description": "Enterprise-ready Java web boilerplate.", "category": "Backend", "language": "Java"},
        {"id": "flutter-provider-starter", "name": "Flutter State Management", "description": "Provider-based mobile app starter.", "category": "Mobile", "language": "Dart"},
        {"id": "react-native-expo", "name": "Expo Router Boilerplate", "description": "File-based routing for cross-platform apps.", "category": "Mobile", "language": "JavaScript"},
        {"id": "nestjs-microservice", "name": "NestJS Microservice Hub", "description": "RabbitMQ and Redis transport pre-configured.", "category": "Backend", "language": "TypeScript"},
        {"id": "remix-run-stack", "name": "Remix Indie Stack", "description": "SQLite, Prisma, and Tailwind CSS.", "category": "Fullstack", "language": "TypeScript"},
        {"id": "eleventy-pure-css", "name": "Eleventy Blog Starter", "description": "Blazing fast blog with 0 JavaScript.", "category": "Static Site", "language": "Liquid"},
        {"id": "solid-start-base", "name": "SolidStart + Prisma", "description": "Modern reactive full-stack boilerplate.", "category": "Fullstack", "language": "JavaScript"},
        {"id": "tauri-desktop-app", "name": "Tauri + Vite + Rust", "description": "Lightweight desktop app boilerplate.", "category": "Desktop", "language": "Rust"},
        {"id": "electron-forge-react", "name": "Electron Forge React", "description": "Standard desktop app with React UI.", "category": "Desktop", "language": "JavaScript"},
        {"id": "deno-fresh-minimal", "name": "Deno Fresh Starter", "description": "Island architecture on the edge.", "category": "Fullstack", "language": "TypeScript"},
        {"id": "bun-hono-api", "name": "Bun + Hono Fast API", "description": "Fastest Node-compatible API starter.", "category": "Backend", "language": "TypeScript"},
        {"id": "nuxt3-module-boilerplate", "name": "Nuxt 3 Module Starter", "description": "Develop and publish Nuxt plugins.", "category": "Framework", "language": "TypeScript"},
        {"id": "jekyll-chirpy", "name": "Jekyll Professional Blog", "description": "Feature-rich theme with dark mode.", "category": "Static Site", "language": "Ruby"},
        {"id": "hugo-blowfish", "name": "Hugo Blowfish Theme", "description": "Extremely fast and flexible Hugo site.", "category": "Static Site", "language": "Go"},
        {"id": "capacitor-ios-android", "name": "Capacitor Mobile Shell", "description": "Turn any Web App into a native app.", "category": "Mobile", "language": "JavaScript"},
        {"id": "quasar-cross-platform", "name": "Quasar Framework UI", "description": "One codebase for Web, Mobile, and Desktop.", "category": "Fullstack", "language": "Vue"},
        {"id": "phoenix-elixir-liveview", "name": "Phoenix LiveView SaaS", "description": "Real-time web apps with Elixir.", "category": "Fullstack", "language": "Elixir"},
        {"id": "strapi-headless-cms", "name": "Strapi 5 Beta Starter", "description": "Ready-to-use CMS with GraphQL.", "category": "Backend", "language": "JavaScript"}
    ],
    "jobs-directory": [
        {"id": "wework-remotely", "name": "We Work Remotely", "description": "The largest remote work community in the world.", "category": "Remote", "url": "https://weworkremotely.com/"},
        {"id": "hacker-news-jobs", "name": "HN 'Who is Hiring'", "description": "Monthly thread of top Silicon Valley tech jobs.", "category": "Tech", "url": "https://hn.algolia.com/?query=Who%20is%20hiring"},
        {"id": "otta-curated-jobs", "name": "Otta", "description": "Personalized job discovery for the best tech startups.", "category": "Startup", "url": "https://otta.com/"},
        {"id": "remoteok-jobs", "name": "Remote OK", "description": "Global remote jobs in tech, design, and marketing.", "category": "Remote", "url": "https://remoteok.com/"},
        {"id": "angellist-startup", "name": "Wellfound (AngelList)", "description": "Hire and get hired at startups and top crypto firms.", "category": "Startup", "url": "https://wellfound.com/"},
        {"id": "flexjobs-remote", "name": "FlexJobs", "description": "Verified remote and flexible jobs across 50 categories.", "category": "Professional", "url": "https://www.flexjobs.com/"},
        {"id": "glassdoor-local", "name": "Glassdoor", "description": "Job listings with verified salary and culture data.", "category": "Corporate", "url": "https://www.glassdoor.com/"},
        {"id": "indeed-global", "name": "Indeed", "description": "The most visited job board globally for all sectors.", "category": "General", "url": "https://www.indeed.com/"},
        {"id": "linkedin-jobs", "name": "LinkedIn Jobs", "description": "Professional networking and job matching.", "category": "Professional", "url": "https://www.linkedin.com/jobs/"},
        {"id": "cryptonary-jobs", "name": "Crypto Jobs List", "description": "Niche jobs in Web3, DeFi, and NFTs.", "category": "Crypto", "url": "https://cryptojobslist.com/"},
        {"id": "design-remotely", "name": "Dribbble Jobs", "description": "Exclusive design roles at top agencies and startups.", "category": "Design", "url": "https://dribbble.com/jobs"},
        {"id": "python-org-jobs", "name": "Python.org Jobs", "description": "Official Python software foundation job board.", "category": "Language Specific", "url": "https://www.python.org/jobs/"},
        {"id": "js-remotely", "name": "JS Remotely", "description": "Curated JavaScript and Frontend remote jobs.", "category": "Language Specific", "url": "https://jsremotely.com/"},
        {"id": "ruby-remotely", "name": "Ruby On Remote", "description": "Remote Ruby and Rails developer jobs.", "category": "Language Specific", "url": "https://rubyonremote.com/"},
        {"id": "go-remote-jobs", "name": "Golang Projects", "description": "Exclusive remote jobs for Go developers.", "category": "Language Specific", "url": "https://golangprojects.com/"},
        {"id": "dice-tech-jobs", "name": "Dice", "description": "Tech-focused job search engine for contractors.", "category": "Tech", "url": "https://www.dice.com/"},
        {"id": "hired-matching", "name": "Hired", "description": "Reverse job board where companies apply to you.", "category": "Tech", "url": "https://hired.com/"},
        {"id": "toptal-network", "name": "Toptal", "description": "Exclusive network of the top 3% of freelancers.", "category": "Freelance", "url": "https://www.toptal.com/"},
        {"id": "upwork-market", "name": "Upwork", "description": "The world's work marketplace for freelancers.", "category": "Freelance", "url": "https://www.upwork.com/"},
        {"id": "fiverr-services", "name": "Fiverr Pro", "description": "High-end marketplace for creative services.", "category": "Freelance", "url": "https://www.fiverr.com/"},
        {"id": "behance-creative", "name": "Behance Jobs", "description": "Adobe's creative portfolio and job network.", "category": "Design", "url": "https://www.behance.net/joblist"},
        {"id": "tech-grad-jobs", "name": "Gradcracker", "description": "STEM careers for graduates and interns in the UK.", "category": "Graduate", "url": "https://www.gradcracker.com/"},
        {"id": "internships-com", "name": "Internships.com", "description": "The largest database of student internships.", "category": "Internship", "url": "https://www.internships.com/"},
        {"id": "remote-woman", "name": "Remote Woman", "description": "Female-friendly remote jobs from top companies.", "category": "Diversity", "url": "https://remotewoman.com/"},
        {"id": "powertofly", "name": "PowerToFly", "description": "Connects multi-cultural talent to tech roles.", "category": "Diversity", "url": "https://powertofly.com/"},
        {"id": "authentic-jobs", "name": "Authentic Jobs", "description": "Jobs for designers, developers, and creatives.", "category": "Design", "url": "https://authenticjobs.com/"},
        {"id": "smashing-magazine", "name": "Smashing Jobs", "description": "Quality job postings from Smashing Magazine.", "category": "Design", "url": "https://www.smashingmagazine.com/jobs/"},
        {"id": "crunchboard", "name": "CrunchBoard", "description": "The official job board of TechCrunch.", "category": "Startup", "url": "https://www.crunchboard.com/"},
        {"id": "it-jobs-gov", "name": "USAJobs (IT)", "description": "Official US government tech job listings.", "category": "Government", "url": "https://www.usajobs.gov/"},
        {"id": "no-desk-remote", "name": "NoDesk", "description": "Curated collection of remote work and tech jobs.", "category": "Remote", "url": "https://nodesk.co/"}
    ],
    "apistatus-directory": [
        {"id": "github-status", "name": "GitHub Status", "description": "Real-time status for GitHub.com and API.", "category": "DevOps", "url": "https://www.githubstatus.com/"},
        {"id": "cloudflare-status", "name": "Cloudflare Systems", "description": "Global network and edge computing status.", "category": "Infrastructure", "url": "https://www.cloudflarestatus.com/"},
        {"id": "aws-health-dash", "name": "AWS Health Dashboard", "description": "Live status of all AWS regions and services.", "category": "Infrastructure", "url": "https://health.aws.amazon.com/"},
        {"id": "stripe-status", "name": "Stripe API Status", "description": "Payments, dashboard, and webhooks status.", "category": "Fintech", "url": "https://status.stripe.com/"},
        {"id": "openai-status", "name": "OpenAI API Health", "description": "ChatGPT and API uptime and incidents.", "category": "AI", "url": "https://status.openai.com/"},
        {"id": "vercel-status", "name": "Vercel Incident Log", "description": "Deployment platform and edge network status.", "category": "Hosting", "url": "https://www.vercel-status.com/"},
        {"id": "netlify-status", "name": "Netlify Systems", "description": "Build, DNS, and CDN performance status.", "category": "Hosting", "url": "https://www.netlifystatus.com/"},
        {"id": "google-cloud-status", "name": "GCP Status Dashboard", "description": "Live updates for Google Cloud services.", "category": "Infrastructure", "url": "https://status.cloud.google.com/"},
        {"id": "azure-status", "name": "Microsoft Azure Status", "description": "Global status of Microsoft Azure services.", "category": "Infrastructure", "url": "https://azure.status.microsoft/"},
        {"id": "digitalocean-status", "name": "DigitalOcean Health", "description": "Droplets, Managed DB, and App Platform status.", "category": "Hosting", "url": "https://status.digitalocean.com/"},
        {"id": "heroku-status", "name": "Heroku Uptime", "description": "Dynos, Data, and Core API status pages.", "category": "Hosting", "url": "https://status.heroku.com/"},
        {"id": "datadog-status", "name": "Datadog Platform", "description": "Monitoring and observability platform health.", "category": "Monitoring", "url": "https://status.datadoghq.com/"},
        {"id": "sentry-status", "name": "Sentry Error Tracking", "description": "Real-time status for Sentry.io services.", "category": "Development", "url": "https://status.sentry.io/"},
        {"id": "mongo-atlas-status", "name": "MongoDB Atlas Status", "description": "Cloud database and search performance.", "category": "Database", "url": "https://status.mongodb.com/"},
        {"id": "supabase-status", "name": "Supabase Infrastructure", "description": "Database, Auth, and Storage status.", "category": "Backend", "url": "https://status.supabase.com/"},
        {"id": "postman-status", "name": "Postman API Platform", "description": "Status of Postman app and cloud services.", "category": "API", "url": "https://status.postman.com/"},
        {"id": "discord-status", "name": "Discord Platform", "description": "Voice, text, and API gateway health.", "category": "Social", "url": "https://discordstatus.com/"},
        {"id": "slack-status", "name": "Slack Service Health", "description": "Messaging and API platform availability.", "category": "Productivity", "url": "https://status.slack.com/"},
        {"id": "zoom-status", "name": "Zoom Video Systems", "description": "Webinar, meetings, and phone status.", "category": "Communication", "url": "https://status.zoom.us/"},
        {"id": "twilio-status", "name": "Twilio Communication", "description": "SMS, Voice, and Messaging API logs.", "category": "Communication", "url": "https://status.twilio.com/"},
        {"id": "mailgun-status", "name": "Mailgun Email API", "description": "Email delivery and API performance logs.", "category": "Marketing", "url": "https://status.mailgun.com/"},
        {"id": "sendgrid-status", "name": "Twilio SendGrid", "description": "Global email delivery infrastructure health.", "category": "Marketing", "url": "https://status.sendgrid.com/"},
        {"id": "intercom-status", "name": "Intercom Business Messaging", "description": "Dashboard and messenger visibility.", "category": "Support", "url": "https://www.intercomstatus.com/"},
        {"id": "zendesk-status", "name": "Zendesk Support", "description": "Helpdesk and ticketing system availability.", "category": "Support", "url": "https://status.zendesk.com/"},
        {"id": "hubspot-status", "name": "HubSpot CRM Systems", "description": "Sales, marketing, and CMS hub health.", "category": "Marketing", "url": "https://status.hubspot.com/"},
        {"id": "atlassian-status", "name": "Jira & Confluence", "description": "Atlassian cloud products status page.", "category": "Productivity", "url": "https://status.atlassian.com/"},
        {"id": "trello-status", "name": "Trello Board Status", "description": "Web, mobile, and API availability for Trello.", "category": "Productivity", "url": "https://trello.status.atlassian.com/"},
        {"id": "notion-status", "name": "Notion Desktop & API", "description": "Workspace and collaborative editor status.", "category": "Productivity", "url": "https://status.notion.so/"},
        {"id": "figma-status", "name": "Figma Design Tool", "description": "Collaborative design and prototyping status.", "category": "Design", "url": "https://status.figma.com/"},
        {"id": "canva-status", "name": "Canva Design Systems", "description": "Graphics platform and printing status.", "category": "Design", "url": "https://www.canvastatus.com/"}
    ]
}

root_dir = r"h:\boring"
for name, items in data.items():
    db_path = os.path.join(root_dir, "projects", name, "data", "database.json")
    if os.path.exists(db_path):
        # Inject generic URLs if missing
        for item in items:
            if "url" not in item:
                if name == "boilerplates-directory":
                    item["url"] = f"https://github.com/search?q={item.get('id', item.get('slug', ''))}"
                elif name == "cheatsheets-directory":
                    item["url"] = f"https://devdocs.io/#q={item.get('id', item.get('slug', ''))}"
                else:
                    item["url"] = f"https://google.com/search?q={item.get('id', item.get('slug', ''))}"

        with open(db_path, "w", encoding="utf-8") as f:
            json.dump(items, f, indent=2, ensure_ascii=False)
        print(f"Updated {db_path} with {len(items)} items.")

print("Data expansion complete.")
